-- Per-product specifications.
--
-- A key-value table rather than columns on products, because the attributes
-- genuinely differ: a panel has a cell count and a module efficiency, a battery
-- has a chemistry and a cycle life, a mounting kit has a wind load. Columns
-- would mean a wide table that is mostly null.
--
-- ============================================================================
-- THE VALUES BELOW ARE PLACEHOLDERS. THEY WERE NOT TAKEN FROM ANY DATASHEET.
--
-- They exist so the page has something to render and so the shape is right.
-- Publishing invented dimensions or warranty terms to real customers is worse
-- than publishing none: someone orders panels that do not fit their roof, or
-- believes a warranty that does not exist. Replace every row with the
-- manufacturer's own figures before selling against them.
-- ============================================================================
--
-- The value column is called spec_value because VALUE is a reserved word in
-- H2, which refuses the CREATE TABLE outright. Postgres and MySQL accept it,
-- so this only shows up on the dialect the tests run against -- which is
-- exactly why they run against one.

CREATE TABLE product_specs (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT       NOT NULL,
    label      VARCHAR(80)  NOT NULL,
    spec_value VARCHAR(160) NOT NULL,
    sort_order INTEGER      NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_product_specs_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_product_specs_product ON product_specs (product_id);

-- sort_order fixes the reading order; the most important figure first.
-- 450W Monocrystalline Panel
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Peak power', '450 W', 0 FROM products WHERE name = '450W Monocrystalline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Cell type', '60-cell monocrystalline PERC', 1 FROM products WHERE name = '450W Monocrystalline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Module efficiency', '21.3%', 2 FROM products WHERE name = '450W Monocrystalline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Dimensions', '1722 x 1134 x 30 mm', 3 FROM products WHERE name = '450W Monocrystalline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Weight', '21.5 kg', 4 FROM products WHERE name = '450W Monocrystalline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Product warranty', '12 years', 5 FROM products WHERE name = '450W Monocrystalline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Performance warranty', '25 years to 84.8% output', 6 FROM products WHERE name = '450W Monocrystalline Panel';

-- 410W Slimline Panel
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Peak power', '410 W', 0 FROM products WHERE name = '410W Slimline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Cell type', '48-cell all-black monocrystalline', 1 FROM products WHERE name = '410W Slimline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Module efficiency', '20.8%', 2 FROM products WHERE name = '410W Slimline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Dimensions', '1622 x 1134 x 30 mm', 3 FROM products WHERE name = '410W Slimline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Weight', '19.5 kg', 4 FROM products WHERE name = '410W Slimline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Product warranty', '12 years', 5 FROM products WHERE name = '410W Slimline Panel';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Performance warranty', '25 years to 84.8% output', 6 FROM products WHERE name = '410W Slimline Panel';

-- 5kW Hybrid Inverter
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Rated AC output', '5 kW', 0 FROM products WHERE name = '5kW Hybrid Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Phases', 'Single phase', 1 FROM products WHERE name = '5kW Hybrid Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Battery support', '48 V, high-voltage ready', 2 FROM products WHERE name = '5kW Hybrid Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'MPPT trackers', '2', 3 FROM products WHERE name = '5kW Hybrid Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Peak efficiency', '97.6%', 4 FROM products WHERE name = '5kW Hybrid Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Dimensions', '470 x 380 x 180 mm', 5 FROM products WHERE name = '5kW Hybrid Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Weight', '17 kg', 6 FROM products WHERE name = '5kW Hybrid Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Warranty', '10 years', 7 FROM products WHERE name = '5kW Hybrid Inverter';

-- 3.6kW String Inverter
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Rated AC output', '3.6 kW', 0 FROM products WHERE name = '3.6kW String Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Phases', 'Single phase', 1 FROM products WHERE name = '3.6kW String Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Battery support', 'None -- grid and solar only', 2 FROM products WHERE name = '3.6kW String Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'MPPT trackers', '1', 3 FROM products WHERE name = '3.6kW String Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Peak efficiency', '97.1%', 4 FROM products WHERE name = '3.6kW String Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Dimensions', '350 x 300 x 145 mm', 5 FROM products WHERE name = '3.6kW String Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Weight', '11 kg', 6 FROM products WHERE name = '3.6kW String Inverter';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Warranty', '10 years', 7 FROM products WHERE name = '3.6kW String Inverter';

-- 5.2kWh Battery Module
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Usable capacity', '5.2 kWh', 0 FROM products WHERE name = '5.2kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Chemistry', 'LiFePO4', 1 FROM products WHERE name = '5.2kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Nominal voltage', '51.2 V', 2 FROM products WHERE name = '5.2kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Cycle life', '6,000 cycles at 80% depth of discharge', 3 FROM products WHERE name = '5.2kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Dimensions', '700 x 480 x 180 mm', 4 FROM products WHERE name = '5.2kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Weight', '48 kg', 5 FROM products WHERE name = '5.2kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Warranty', '10 years', 6 FROM products WHERE name = '5.2kWh Battery Module';

-- 10.4kWh Battery Module
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Usable capacity', '10.4 kWh', 0 FROM products WHERE name = '10.4kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Chemistry', 'LiFePO4', 1 FROM products WHERE name = '10.4kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Nominal voltage', '51.2 V', 2 FROM products WHERE name = '10.4kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Cycle life', '6,000 cycles at 80% depth of discharge', 3 FROM products WHERE name = '10.4kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Dimensions', '700 x 480 x 340 mm', 4 FROM products WHERE name = '10.4kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Weight', '94 kg', 5 FROM products WHERE name = '10.4kWh Battery Module';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Warranty', '10 years', 6 FROM products WHERE name = '10.4kWh Battery Module';

-- Pitched Roof Mounting Kit (8 panels)
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Panels supported', '8', 0 FROM products WHERE name = 'Pitched Roof Mounting Kit (8 panels)';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Material', 'Anodised aluminium, stainless fixings', 1 FROM products WHERE name = 'Pitched Roof Mounting Kit (8 panels)';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Rail length', '2 rails at 4.4 m', 2 FROM products WHERE name = 'Pitched Roof Mounting Kit (8 panels)';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Roof type', 'Pitched tile or slate', 3 FROM products WHERE name = 'Pitched Roof Mounting Kit (8 panels)';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Rated wind load', 'Up to 130 km/h', 4 FROM products WHERE name = 'Pitched Roof Mounting Kit (8 panels)';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Kit weight', '24 kg', 5 FROM products WHERE name = 'Pitched Roof Mounting Kit (8 panels)';

-- Flat Roof Ballast Frame (4 panels)
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Panels supported', '4', 0 FROM products WHERE name = 'Flat Roof Ballast Frame (4 panels)';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Tilt angle', '10 degrees', 1 FROM products WHERE name = 'Flat Roof Ballast Frame (4 panels)';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Material', 'Anodised aluminium, stainless fixings', 2 FROM products WHERE name = 'Flat Roof Ballast Frame (4 panels)';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Roof type', 'Flat, non-penetrating', 3 FROM products WHERE name = 'Flat Roof Ballast Frame (4 panels)';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Ballast required', 'About 40 kg per frame, supplied separately', 4 FROM products WHERE name = 'Flat Roof Ballast Frame (4 panels)';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Kit weight', '18 kg', 5 FROM products WHERE name = 'Flat Roof Ballast Frame (4 panels)';

-- 7kW Tethered EV Charger
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Output', '7.4 kW', 0 FROM products WHERE name = '7kW Tethered EV Charger';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Connector', 'Tethered Type 2, 5 m cable', 1 FROM products WHERE name = '7kW Tethered EV Charger';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Phases', 'Single phase', 2 FROM products WHERE name = '7kW Tethered EV Charger';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Solar surplus matching', 'Yes', 3 FROM products WHERE name = '7kW Tethered EV Charger';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Ingress rating', 'IP65', 4 FROM products WHERE name = '7kW Tethered EV Charger';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Warranty', '3 years', 5 FROM products WHERE name = '7kW Tethered EV Charger';

-- Consumption Monitoring Kit
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'CT clamps included', '2', 0 FROM products WHERE name = 'Consumption Monitoring Kit';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Sampling interval', '1 second', 1 FROM products WHERE name = 'Consumption Monitoring Kit';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Connectivity', 'Wi-Fi and Ethernet', 2 FROM products WHERE name = 'Consumption Monitoring Kit';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Data retention', '12 months', 3 FROM products WHERE name = 'Consumption Monitoring Kit';
INSERT INTO product_specs (product_id, label, spec_value, sort_order)
    SELECT id, 'Warranty', '2 years', 4 FROM products WHERE name = 'Consumption Monitoring Kit';

