-- Why a stock figure changed.
--
-- Sales, cancellations and refunds all moved stock silently; the only recorded
-- changes were the ones an administrator typed. So "I counted ten onto the
-- shelf and the system says three" had no answer, and a shop whose stock number
-- cannot be explained is one where nobody trusts the stock number.
--
-- Append-only, like admin_actions: written and read, never updated.
CREATE TABLE stock_movements (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    product_id      BIGINT       NOT NULL,
    -- Signed: negative for a sale, positive for stock coming back.
    quantity_change INTEGER      NOT NULL,
    -- Stored rather than derived. Replaying every row to learn what the figure
    -- was on Tuesday means trusting that no row is missing; storing the result
    -- at each step makes a gap show up instead of changing the answer.
    resulting_stock INTEGER      NOT NULL,
    reason          VARCHAR(32)  NOT NULL,
    -- Null for a stock take: somebody counting a shelf, not a customer action.
    order_id        BIGINT,
    -- Null when the shop did it on its own rather than a person.
    actor           VARCHAR(255),
    happened_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_stock_movements_product
        FOREIGN KEY (product_id) REFERENCES products (id)
);

-- The history page reads one product's movements, newest first.
CREATE INDEX idx_stock_movements_product ON stock_movements (product_id, happened_at DESC);
