-- Baseline schema (H2 dialect, used for local development and tests).
--
-- The MySQL equivalent lives in db/migration/mysql. Both are selected by the
-- {vendor} placeholder in spring.flyway.locations. Column types differ between
-- the two by necessity -- H2 wants TIMESTAMP WITH TIME ZONE and NUMERIC where
-- MySQL wants DATETIME and DECIMAL -- so the files cannot be shared.
--
-- Keep this in step with the entities: ddl-auto=validate fails the build when
-- they drift apart.

CREATE TABLE products (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255)  NOT NULL,
    description VARCHAR(2000),
    price       NUMERIC(10, 2) NOT NULL,
    category    VARCHAR(32)   NOT NULL,
    stock       INTEGER       NOT NULL,
    image_url   VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    full_name  VARCHAR(255) NOT NULL,
    role       VARCHAR(16)  NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE cart_items (
    id         BIGINT  GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,
    PRIMARY KEY (id),
    -- One line per product per user; CartService relies on this to merge
    -- repeat adds instead of creating duplicate rows.
    CONSTRAINT uk_cart_items_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_cart_items_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE orders (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id           BIGINT       NOT NULL,
    status            VARCHAR(32)  NOT NULL,
    shipping_name     VARCHAR(255) NOT NULL,
    shipping_address  VARCHAR(255) NOT NULL,
    shipping_postcode VARCHAR(255) NOT NULL,
    placed_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE order_items (
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    order_id     BIGINT         NOT NULL,
    product_id   BIGINT         NOT NULL,
    -- Name and price are snapshots taken at purchase time, deliberately
    -- duplicated from products so a later edit cannot rewrite a placed order.
    product_name VARCHAR(255)   NOT NULL,
    unit_price   NUMERIC(10, 2) NOT NULL,
    quantity     INTEGER        NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_orders_user ON orders (user_id);
CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_cart_items_user ON cart_items (user_id);
