-- Baseline schema (MySQL dialect).
--
-- Mirrors db/migration/h2/V1__initial_schema.sql. The two differ only where
-- the dialects force it: DATETIME(6) vs TIMESTAMP WITH TIME ZONE, DECIMAL vs
-- NUMERIC, AUTO_INCREMENT vs GENERATED BY DEFAULT AS IDENTITY.
--
-- Column types here were generated from the entities with Hibernate's MySQL
-- dialect, so ddl-auto=validate should accept them. See the README for why
-- this file is worth smoke-testing against a real MySQL before you rely on it.

CREATE TABLE products (
    id          BIGINT         NOT NULL AUTO_INCREMENT,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(2000),
    price       DECIMAL(10, 2) NOT NULL,
    category    VARCHAR(32)    NOT NULL,
    stock       INTEGER        NOT NULL,
    image_url   VARCHAR(255),
    PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE users (
    id         BIGINT       NOT NULL AUTO_INCREMENT,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    full_name  VARCHAR(255) NOT NULL,
    role       VARCHAR(16)  NOT NULL,
    created_at DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
) ENGINE = InnoDB;

CREATE TABLE cart_items (
    id         BIGINT  NOT NULL AUTO_INCREMENT,
    user_id    BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,
    PRIMARY KEY (id),
    -- One line per product per user; CartService relies on this to merge
    -- repeat adds instead of creating duplicate rows.
    CONSTRAINT uk_cart_items_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_cart_items_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id)
) ENGINE = InnoDB;

CREATE TABLE orders (
    id                BIGINT       NOT NULL AUTO_INCREMENT,
    user_id           BIGINT       NOT NULL,
    status            VARCHAR(32)  NOT NULL,
    shipping_name     VARCHAR(255) NOT NULL,
    shipping_address  VARCHAR(255) NOT NULL,
    shipping_postcode VARCHAR(255) NOT NULL,
    placed_at         DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE = InnoDB;

CREATE TABLE order_items (
    id           BIGINT         NOT NULL AUTO_INCREMENT,
    order_id     BIGINT         NOT NULL,
    product_id   BIGINT         NOT NULL,
    -- Name and price are snapshots taken at purchase time, deliberately
    -- duplicated from products so a later edit cannot rewrite a placed order.
    product_name VARCHAR(255)   NOT NULL,
    unit_price   DECIMAL(10, 2) NOT NULL,
    quantity     INTEGER        NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id)
) ENGINE = InnoDB;

CREATE INDEX idx_orders_user ON orders (user_id);
CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_cart_items_user ON cart_items (user_id);
